import type { Metadata } from 'next'
import './globals.css'
import { TailwindIndicator } from '@/components/base/tailwind-indicator'
import Provider from '@/components/providers/provider'
import { fraunces, merriweatherSans, mono } from '@/lib/fonts'
import { cn } from '@/lib/utils'
// import { Toaster } from '@/components/ui/sonner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          merriweatherSans.variable,
          fraunces.variable,
          mono.variable,
          'bg-background font-sans text-foreground antialiased',
        )}
      >
        <Provider>{children}</Provider>
        <TailwindIndicator />
        {/* <Toaster closeButton /> */}
      </body>
    </html>
  )
}
